name: Camden

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: target cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Build
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Store binary
        uses: actions/upload-artifact@v3
        with:
          name: camden-server
          path: target/release/camden
      - name: webhook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: "${{ secrets.FETCHER_URL }}"
          webhook_secret: "${{ secrets.FETCHER_SECRET }}"
          webhook_type: json
          data: '{"run_id": ${{ github.run_id }}}'
